# https://github.com/rojo-rbx/rokit

[tools]
rojo = "rojo-rbx/rojo@7.5.1"
wally = "UpliftGames/wally@0.3.2"
wally-package-types = "JohnnyMorganz/wally-package-types@1.5.1"
selene = "Kampfkarren/selene@0.29.0"
run-in-roblox = "rojo-rbx/run-in-roblox@0.3.0"

# ok.